# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Site Information
site_author: Cassidyllic, Osaka, and Ren
site_description: A comprehensive wiki for Delta Warriors.
site_name: Delta Warriors Wiki
site_url: https://cassidyllic.github.io/delta-warriors-wiki

copyright: Deltarune &copy; by Toby Fox | Delta Warriors by Idyll Works - This wiki is an open source project under the GNU GPL v3 license.

# Extra Configuration
extra:
  social:
    - icon: simple/discord
      link: https://discord.gg/9v5CMsqrAc
      name: Official Discord server
    - icon: simple/robloxstudio
      link: https://www.roblox.com/communities/7344131/Idyll-Works#!/about
      name: Official Roblox community
    - icon: brand/deltarune
      link: https://deltarune.com/
      name: Deltarune by Toby Fox

extra_css:
  - content/css/stylesheet.css

# Extensions & Plugins
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: fr
          build: false
          copyright: Deltarune&copy;, Toby Fox | Delta Warriors, Idyll Works - Ce wiki est un projet open source sous licence GNU GPL v3.
          name: Français
          nav_translations:
            Home: Accueil
            Credits: Crédits
            Updates: Mises à jour
          site_name: Wiki Delta Warriors

        - locale: ja
          build: false
          copyright: 『DELTARUNE&copy;』Toby Fox | 『デルタウォリアーズ』 Idyll Works制作 - Wikiはオープンソースです
          name: 日本語
          nav_translations:
            Home: ホームページ
            Credits: クレジット
            Updates: アップデート
          site_name: デルタウォリアーズ Wiki

        # To be added.
        - locale: pt-BR
          name: Português Brasileiro
          build: false
  - macros
  - meta
  - search

# Navigation
nav:
  - Home:
      - index.md
  # - Soul Traits:
  #     - souls/index.md
  #     - Bravery: souls/bravery.md
  # - Equipment:
  #     - equipment/index.md
  #     - Weapons:
  #         - equipment/weapons/index.md
  #     - Accessories:
  #         - equipment/accessories/index.md
  # - Locations:
  #     - locations/index.md
  #     - Hometown:
  #         - locations/hometown/index.md
  #     - Closet Dark World:
  #         - locations/closet-world/index.md
  # - NPCs:
  #     - npcs/index.md

# Theme Configuration
theme:
  custom_dir: theme
  favicon: content/img/deltarune.svg
  features:
    - content.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.share
    - search.suggest
  font:
    text: Raleway
  icon:
    annotation: material/information
  name: material
  palette:
    accent: custom
    primary: custom
    scheme: slate

# Serve convenience
watch:
  - includes
  - theme
