# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Site Information
site_author: Cassidyllic
site_description: A comprehensive wiki for Delta Warriors
site_name: Delta Warriors Wiki
site_url: https://cassidyllic.github.io/delta-warriors-wiki

copyright: Deltarune &copy; by Toby Fox | Delta Warriors by Idyll Works - Wiki is Open Source

# Extra Configuration
extra:
  social:
    - icon: simple/discord
      link: https://discord.gg/9v5CMsqrAc
      name: Official Discord server
    - icon: simple/robloxstudio
      link: https://www.roblox.com/communities/7344131/Idyll-Works#!/about
      name: Official Roblox community
    - icon: custom/deltarune
      link: https://deltarune.com/
      name: Deltarune by Toby Fox

extra_css:
  - css/components.css
  - css/stylesheet.css
  - css/utilities.css

# Extensions & Plugins
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: false
          nav_translations:
            Home: Accueil
            Mechanics: Mécaniques
            Soul Traits: Âmes
            Equipment: Équipement
            Weapons: Armes
            Accessories: Accessoires
            Locations: Lieux
            NPCs: PNJs
        - locale: ja
          name: 日本語
          build: false
        - locale: pt-BR
          name: Português Brasileiro
          build: false
  - macros
  - meta
  - search

# Navigation
nav:
  - Home:
      - index.md
      - Credits: credit.md
      - Updates:
          - updates/index.md
          - 1.0.0: updates/v1-0-0.md
  - Mechanics:
      - mechanics/index.md
      - The Survey: mechanics/introduction.md
      - Rarities: mechanics/rarities.md
      - Fountains: mechanics/fountains.md
      - Experience: mechanics/exp.md
      - Upgrades: mechanics/growth.md
  - Soul Traits:
      - souls/index.md
      - Bravery: souls/bravery.md
  - Equipment:
      - equipment/index.md
      - Weapons:
          - equipment/weapons/index.md
      - Accessories:
          - equipment/accessories/index.md
  - Locations:
      - locations/index.md
      - Hometown:
          - locations/hometown/index.md
      - Closet Dark World:
          - locations/closet-world/index.md
  - NPCs:
      - npcs/index.md

not_in_nav: |
  en/debugPage.md

# Theme Configuration
theme:
  custom_dir: overrides
  favicon: assets/img/deltarune.svg
  features:
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.share
    - search.suggest
  font:
    text: Raleway
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Dark Mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Light Mode
